name: Automatic Update of Manifest

on:
  pull_request:
    branches:
      - main

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Get current draft release info
        id: draft_release_info
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
          draft: true

      - name: Save version
        id: version
        run: | 
          VERSION=${{ steps.draft_release_info.outputs.tag_name }}
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Update manifest.json version
        uses: restackio/update-json-values-action@v1.0.0
        with:
          file: manifest.json
          values: "{\"version\": $VERSION}"

      - name: Commit file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifest.json
          git commit -m "action: uplift manifest version to version $VERSION"
          git push
