name: Automatic Update of Manifest

on:
  pull_request:
    branches:
      - main

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get current draft release info
        id: draft_release_info
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
          draft: true

      - name: Save version
        id: version
        run: | 
          VERSION=${{ steps.draft_release_info.outputs.tag_name }}
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: manifest.json
          field: version
          value: $VERSION

      - name: Commit file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "action: uplift manifest version to version $VERSION"
        
      - name: Push change
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
