name: Build and Release Extension

on:
  release:
    types: [published]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |-
          zip -r audible-volume-control-${{ github.event.pull_request.head.sha }}.zip .

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: audible-volume-control-${{ github.sha }}
          path: audible-volume-control-${{ github.event.pull_request.head.sha }}.zip
          
  release-extension:
    needs: build-extension
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: audible-volume-control-${{ github.sha }}

      - name: Release chrome extension
        uses: browser-actions/release-chrome-extension@latest
        with:
          extension-id: "djbhnpbemmoeenglcdojbkmpdmlcgeoi"
          extension-path: "audible-volume-control-${{ github.event.pull_request.head.sha }}.zip"
          oauth-client-id: ${{ secrets.G_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.G_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.G_REFRESH_TOKEN }}

      - name: Release firefox addon
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: "audible-volume-control"
          addon-path: "audible-volume-control-${{ github.event.pull_request.head.sha }}.zip"
          auth-api-issuer: ${{ secrets.F_API_ISSUER }}
          auth-api-secret: ${{ secrets.F_API_SECRET }}
