name: Build and Release Extension

on:
  release:
    types: [published]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get semantic release info
        id: semantic_release_info
        uses: jossef/action-semantic-release-info@v2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: manifest.json
          field: version
          value: ${{ steps.semantic_release_info.outputs.version }}
      
      - name: Commit file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "action: uplift manifest version to ${{ steps.semantic_release_info.outputs.git_tag }}"
        
      - name: Push change
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}

      - name: Build
        run: |-
          cat manifest.json
          zip -r audible-volume-control-${{ github.event.pull_request.head.sha }}.zip .

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: audible-volume-control-${{ github.sha }}
          path: audible-volume-control-${{ github.event.pull_request.head.sha }}.zip
          
  release-chrome-extension:
    needs: build-extension
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: audible-volume-control-${{ github.sha }}

      - name: Release chrome extension
        uses: browser-actions/release-chrome-extension@latest
        with:
          extension-id: "djbhnpbemmoeenglcdojbkmpdmlcgeoi"
          extension-path: "audible-volume-control-${{ github.event.pull_request.head.sha }}.zip"
          oauth-client-id: ${{ secrets.G_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.G_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.G_REFRESH_TOKEN }}

  release-firefox-addon:
     needs: build-extension
     runs-on: ubuntu-latest
     steps:
       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
           name: audible-volume-control-${{ github.sha }}

       - name: Release firefox addon
         uses: browser-actions/release-firefox-addon@latest
         with:
           addon-id: "audible-volume-control"
           addon-path: "audible-volume-control-${{ github.event.pull_request.head.sha }}.zip"
           auth-api-issuer: ${{ secrets.F_API_ISSUER }}
           auth-api-secret: ${{ secrets.F_API_SECRET }}
