name: Build and Release Extension

on:
  release:
    types: [published]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |-
          cat manifest.json
          zip -r audible-volume-control-${{ github.sha }}.zip . --exclude '*.git*'

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: audible-volume-control-${{ github.sha }}
          path: audible-volume-control-${{ github.sha }}.zip

  release-chrome-extension:
    needs: build-extension
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: audible-volume-control-${{ github.sha }}

      - name: Release chrome extension
        uses: browser-actions/release-chrome-extension@latest
        with:
          extension-id: "djbhnpbemmoeenglcdojbkmpdmlcgeoi"
          extension-path: "audible-volume-control-${{ github.sha }}.zip"
          oauth-client-id: ${{ secrets.G_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.G_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.G_REFRESH_TOKEN }}

  release-firefox-addon:
     needs: build-extension
     runs-on: ubuntu-latest
     steps:
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
           name: audible-volume-control-${{ github.sha }}

       - name: Release firefox addon
         uses: cardinalby/webext-buildtools-firefox-addons-action@v1
         with:
           zipFilePath: 'audible-volume-control-${{ github.sha }}.zip'
           extensionId: '{6416fba2-1151-4e0b-ad65-1c36b3994ef1}'
           jwtIssuer: ${{ secrets.F_API_ISSUER }}
           jwtSecret: ${{ secrets.F_API_SECRET }}
